#!/bin/bash
#SBATCH --time=72:00:00   # walltime
#SBATCH --ntasks=3   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=4GB   # memory per CPU core
#SBATCH --account=introtogds
#SBATCH -J "iqtree.job"   # job name
#SBATCH --mail-user=<username>@vt.com   # email address
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL


iqtree-2.3.6-Linux-intel/bin/iqtree2 -s 129755at50557_aligned.fas 
