---
title: "Creating scatter plots and heatmap"
output: html_notebook
---

# Install the required package - phyloseq. Uncomment this code snip-it if you need it.
```{r}
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("phyloseq")
```
# Load the package, setting working directory, and call the datasets
```{r}
library(phyloseq)
library(ggplot2)
library(vegan)

setwd("/Users/Windows10/rstudio/i2gds/project_microplastic/") # change this to your working directory - the place where all your files are located

boo_wels_o_phyobj <- readRDS("boo_wels_o_phyloseq.rds")
taxa <- readRDS("boo_wels_o_taxa.rds")
sample.names <- readRDS("boo_wels_o_sample.names.rds")

sample_data <- read.csv("meta_data_2.csv")
sample_data$Species <- ifelse(sample_data$Species == 'boo', 'L. booriae', 
                              ifelse(sample_data$Species == 'wels', 'L. welshimeri', 
                                     sample_data$Species))
```

# Creating an ordination plot comparing the beta diversity of 2 groups
```{r}
# Identify empty rows
empty_rows <- which(rowSums(otu_table(boo_wels_o_phyobj)) == 0)

# Filter out empty rows
boo_wels_o_phyobj_bray_pcoa <- prune_samples(sample_names(boo_wels_o_phyobj)[-empty_rows], boo_wels_o_phyobj)

# Perform ordination on the filtered data
ordination1 <- ordinate(boo_wels_o_phyobj_bray_pcoa, method = "PCoA", distance = "bray")

# Create the plot
plot1 <- plot_ordination(boo_wels_o_phyobj_bray_pcoa, ordination1, color="Species", title="Bray PCoA") +
  geom_point(size=2) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),  # Remove grid lines
    axis.line = element_line(color = "black"),  # Add axis lines
    panel.border = element_rect(color = "black", fill = NA)
  )

# Add 95% CI around the data points
plot1 <- plot1 + stat_ellipse(level = 0.95)

# Calculate Bray-Curtis dissimilarity
braydist <- phyloseq::distance(boo_wels_o_phyobj, method = "bray")

# Perform PERMANOVA
permanova_result <- adonis2(braydist ~ Species, data = sample_data, permutations = 999)

# Extract p-value from PERMANOVA result
p_value <- permanova_result$`Pr(>F)`
p_value <- p_value[!is.na(p_value)]

# Add p-value annotation to the plot
plot1 <- plot1 +
  annotate(
    "text",
    x = 0.15,
    y = -0.5,
    label = paste("PERMANOVA P =", p_value),
    size = 4.5  # Increase the font size
  )

# Safe the plot
ggsave("bray_pcoa_plot.png", plot = plot1, device = "png", width = 8, height = 6)

# Show the plot
plot1
```

# Creating a heatmap for presence/absence matrix
```{r}
# Load the library
library(reshape2)
library(pheatmap)

# Load the data
data <- read.csv("arg_pre_abs.csv", row.names = 1)

# Convert data to matrix
data_matrix <- as.matrix(data)

# Generate the heatmap
plot_2 <- pheatmap(
  data_matrix,
  color = colorRampPalette(c("lightgrey", "navy"))(50), # Color gradient
  cluster_rows = FALSE,                              # Add row dendrogram
  cluster_cols = FALSE,                              # Add column dendrogram
  main = "Heatmap of Antimicrobial Resistance Genes", # Title
  fontsize_row = 8,                                 # Row font size
  fontsize_col = 8,                                 # Column font size
  border_color = NA                                 # Remove lines inside the heatmap
)

# Safe the plot
ggsave("heatmap.png", plot = plot_2, device = "png", width = 8, height = 6)
```
