# Description: Collects all .faa files generated by Prodigal analysis
# Working directory: /projects/intro2gds/I2GDS2024/individual_folders/manisha/
# Input directories: results/03_prodigal/sample_subdirectories/
# Output directory: results/03_prodigal/all_faa_files/
# Author: Manisha Chaudhary
# Date: 09/28/2024

# Set the directory where the Prodigal results are stored
INPUT_DIR="results/03_prodigal"
FAA_DIR="$INPUT_DIR/all_faa_files"

# Create a directory for the .faa files if it doesn't exist
mkdir -p "$FAA_DIR"

# Find all .faa files in the subdirectories of INPUT_DIR and move them to FAA_DIR
find "$INPUT_DIR" -type f -name "*.faa" | while read -r faa_file; do
    # Move each .faa file to the all_faa_files directory
    echo "Moving $faa_file to $FAA_DIR"
    cp "$faa_file" "$FAA_DIR/"
done

echo "All .faa files have been moved to $FAA_DIR."
